//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezProjesi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TezProjesi.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string adres {
            get {
                return ResourceManager.GetString("adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string anasayfa {
            get {
                return ResourceManager.GetString("anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string ara {
            get {
                return ResourceManager.GetString("ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ay.
        /// </summary>
        public static string ay {
            get {
                return ResourceManager.GetString("ay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Tarihi.
        /// </summary>
        public static string cıkıstarihi {
            get {
                return ResourceManager.GetString("cıkıstarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string cıkısyap {
            get {
                return ResourceManager.GetString("cıkısyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çocuk.
        /// </summary>
        public static string cocuk {
            get {
                return ResourceManager.GetString("cocuk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çocuk Sayısı.
        /// </summary>
        public static string cocuksayisi {
            get {
                return ResourceManager.GetString("cocuksayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        public static string detay {
            get {
                return ResourceManager.GetString("detay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat Aralığı.
        /// </summary>
        public static string fiyataralıgı {
            get {
                return ResourceManager.GetString("fiyataralıgı", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat/Performans Puanı.
        /// </summary>
        public static string fiyatpuan {
            get {
                return ResourceManager.GetString("fiyatpuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gecelik Fiyat.
        /// </summary>
        public static string gecelikfiyat {
            get {
                return ResourceManager.GetString("gecelikfiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genel Puanı.
        /// </summary>
        public static string genelpuan {
            get {
                return ResourceManager.GetString("genelpuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Tarihi.
        /// </summary>
        public static string giristarihi {
            get {
                return ResourceManager.GetString("giristarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string girisyap {
            get {
                return ResourceManager.GetString("girisyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string hakkımızda {
            get {
                return ResourceManager.GetString("hakkımızda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EBG tur çatısı altında hayata geçirdiğimiz alt markalarımız ile konaklama, ulaşım ve acente zincirini kurarak, turizmin tüm gerekliliklerini kapsayan hizmetler sunuyoruz. Otel rezervasyonu ile tüketicinin ihtiyaç ve beklentilerini karşılıyoruz..
        /// </summary>
        public static string hakkimizdametin {
            get {
                return ResourceManager.GetString("hakkimizdametin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hızlı Menü.
        /// </summary>
        public static string hızlımenü {
            get {
                return ResourceManager.GetString("hızlımenü", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string isim {
            get {
                return ResourceManager.GetString("isim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kartın Üzerindeki Ad.
        /// </summary>
        public static string kartınuzerindekiad {
            get {
                return ResourceManager.GetString("kartınuzerindekiad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kart Numarası.
        /// </summary>
        public static string kartnumarası {
            get {
                return ResourceManager.GetString("kartnumarası", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string kaydet {
            get {
                return ResourceManager.GetString("kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydol.
        /// </summary>
        public static string kaydol {
            get {
                return ResourceManager.GetString("kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konum Puanı.
        /// </summary>
        public static string konumpuan {
            get {
                return ResourceManager.GetString("konumpuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda.
        /// </summary>
        public static string oda {
            get {
                return ResourceManager.GetString("oda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Ara.
        /// </summary>
        public static string odaara {
            get {
                return ResourceManager.GetString("odaara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oda Puanı.
        /// </summary>
        public static string odapuan {
            get {
                return ResourceManager.GetString("odapuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ödeme Yap.
        /// </summary>
        public static string odemeyap {
            get {
                return ResourceManager.GetString("odemeyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öne Çıkan Oteller.
        /// </summary>
        public static string onecikanoteller {
            get {
                return ResourceManager.GetString("onecikanoteller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otel.
        /// </summary>
        public static string otel {
            get {
                return ResourceManager.GetString("otel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oteller.
        /// </summary>
        public static string oteller {
            get {
                return ResourceManager.GetString("oteller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popüler Bölgeler.
        /// </summary>
        public static string popülerbölgeler {
            get {
                return ResourceManager.GetString("popülerbölgeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyonlarım.
        /// </summary>
        public static string rezervasyonlarım {
            get {
                return ResourceManager.GetString("rezervasyonlarım", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezervasyon Yap.
        /// </summary>
        public static string rezervasyonyap {
            get {
                return ResourceManager.GetString("rezervasyonyap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçiniz...
        /// </summary>
        public static string seciniz {
            get {
                return ResourceManager.GetString("seciniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servis Puanı.
        /// </summary>
        public static string servispuan {
            get {
                return ResourceManager.GetString("servispuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string sifre {
            get {
                return ResourceManager.GetString("sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sizden Gelen Yorumlar...
        /// </summary>
        public static string sizdengelenyorumlar {
            get {
                return ResourceManager.GetString("sizdengelenyorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soyad.
        /// </summary>
        public static string soyad {
            get {
                return ResourceManager.GetString("soyad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string tarih {
            get {
                return ResourceManager.GetString("tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string telefon {
            get {
                return ResourceManager.GetString("telefon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Fiyat.
        /// </summary>
        public static string toplamfiyat {
            get {
                return ResourceManager.GetString("toplamfiyat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemek Puanı.
        /// </summary>
        public static string yemekpuan {
            get {
                return ResourceManager.GetString("yemekpuan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetişkin.
        /// </summary>
        public static string yetiskin {
            get {
                return ResourceManager.GetString("yetiskin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetişkin Sayısı.
        /// </summary>
        public static string yetiskinsayisi {
            get {
                return ResourceManager.GetString("yetiskinsayisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıl.
        /// </summary>
        public static string yıl {
            get {
                return ResourceManager.GetString("yıl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string yorum {
            get {
                return ResourceManager.GetString("yorum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorum Yap.
        /// </summary>
        public static string yorumyap {
            get {
                return ResourceManager.GetString("yorumyap", resourceCulture);
            }
        }
    }
}
